### 카드 생성
POST http://localhost:8080/cards
Authorization: {{user1Auth}}
Content-Type: application/json

{
  "columnId": 1,
  "cardName": "cardName_3225c6b9ca08",
  "userId": 1,
  "deadline": "2024-07-11"
}

### 카드 생성 - 작업자 없이
POST http://localhost:8080/cards
Authorization: {{user1Auth}}
Content-Type: application/json

{
  "columnId": 1,
  "cardName": "hi",
  "cardContents": "cardContents_b1a81b394d5f",
  "deadline": "2024-07-11"
}

### 카드 생성 - 마감일자 없이
POST http://localhost:8080/cards
Authorization: {{user1Auth}}
Content-Type: application/json

{
  "columnId": 1,
  "cardName": "hi",
  "cardContents": "cardContents_b1a81b394d5f"
}

### 카드 생성 실패
POST http://localhost:8080/cards
Authorization: {{user1Auth}}
Content-Type: application/json

{
  "columnId": 1,
  "cardName": "",
  "cardContents": "cardContents_b1a81b394d5f",
  "userId": 2,
  "deadline": "2024-07-11"
}

### 카드 생성 실패 - 보드 참여자가 아닌 경우
POST http://localhost:8080/cards
Authorization: {{user1Auth}}
Content-Type: application/json

{
  "columnId": 1,
  "cardName": "hi",
  "userId": 4,
  "cardContents": "cardContents_b1a81b394d5f"
}

### 카드 생성 실패 - Validation
POST http://localhost:8080/cards
Authorization: {{user1Auth}}
Content-Type: application/json

{
  "userId": 4,
  "cardContents": "cardContents_b1a81b394d5f",
  "deadline": "2024-07-11"
}

### 카드 생성 실패 - 날짜 형식
POST http://localhost:8080/cards
Content-Type: application/json

{
  "columnId": 1,
  "cardName": "hi",
  "userId": 4,
  "cardContents": "cardContents_b1a81b394d5f",
  "deadline": "20240711"
}

### 카드 단일 조회
GET http://localhost:8080/cards/1
Authorization: {{user1Auth}}


### 컬럼별 카드 리스트 조회
GET http://localhost:8080/cards
Authorization: {{user1Auth}}
Content-Type: application/json

{
  "columnId": 1
}


### 사용자별 컬럼별 카드 리스트 조회(이메일)
GET http://localhost:8080/cards?search=email
Authorization: {{user1Auth}}
Content-Type: application/json

{
  "columnId": 1,
  "workerEmail": "test2@mail.com"
}

### 사용자별 컬럼별 카드 리스트 조회(아이디)
GET http://localhost:8080/cards?search=workerId
Authorization: {{user1Auth}}
Content-Type: application/json

{
  "columnId": 1,
  "workerId": 3
}



### 카드 수정
PATCH http://localhost:8080/cards/1
Content-Type: application/json
Authorization: {{user1Auth}}

{
  "cardName": "제목 수정",
  "cardContents": "카드 수정",
  "deadline": "2024-07-12"
}

### 카드 수정
PATCH http://localhost:8080/cards/1
Authorization: {{user1Auth}}
Content-Type: application/json

{
  "cardName": "제목 왜 지금은 되는거야대체 왜!!!!!",
  "userId": 2,
  "cardContents": "관련 작업 모두 끝내기",
  "deadline": "2024-07-12"
}

### 카드 수정 실패 - 해당 보드 유저가 아님
PATCH http://localhost:8080/cards/1
Authorization: {{user1Auth}}

Content-Type: application/json

{
  "cardName": "제목 수정",
  "userId": 4,
  "cardContents": "카드 수정",
  "deadline": "2024-07-11"
}

### 카드 수정 실패 - 해당 보드 유저가 아님
PATCH http://localhost:8080/cards/1
Authorization: {{user1Auth}}

Content-Type: application/json

{
  "columnId": 2,
  "cardName": "제목 수정",
  "userId": 4,
  "cardContents": "카드 수정",
  "deadline": "2024-07-11"
}

### 카드 삭제
DELETE http://localhost:8080/cards/5
Authorization: {{user1Auth}}