### 컬럼 조회
GET http://localhost:8080/columns
Authorization:{{USER1_TOKEN}}
Content-Type: application/json

{
  "boardId":1
}

### 컬럼 조회
GET http://localhost:8080/columns
Authorization:{{USER1_TOKEN}}
Content-Type: application/json

{
  "boardId":1
}

### 컬럼 생성
POST http://localhost:8080/columns
Authorization:{{USER1_TOKEN}}
Content-Type: application/json

{
  "columnName" : "하이2",
  "boardId" : 1
}

### 컬럼 생성 실패 - 매니저가 아닌 경우
POST http://localhost:8080/columns
Authorization:{{USER2_TOKEN}}
Content-Type: application/json

{
  "columnName" : "test1",
  "boardId" : 1
}

### 컬럼 수정 성공
PATCH http://localhost:8080/columns/1
Authorization:{{USER1_TOKEN}}
Content-Type: application/json

{
  "columnName" : "수정 컬럼"
}

### 컬럼 수정 실패 - 매니저가 아닌 경우
PATCH http://localhost:8080/columns/1
Authorization:{{USER2_TOKEN}}
Content-Type: application/json

{
  "columnName" : "수정 컬럼"
}

### 컬럼 순서 변경
PATCH http://localhost:8080/columns/1/order
Authorization:{{USER1_TOKEN}}
Content-Type: application/json

{
  "orderId" : 3
}

### 컬럼 삭제
DELETE http://localhost:8080/columns/2
Authorization:{{USER1_TOKEN}}

