### 댓글 작성
POST http://localhost:8080/comments
Content-Type: application/json
Authorization: {{USER1_TOKEN}}

{
  "cardId": 3,
  "content": "This is a new comment."
}

### 카드 ID로 댓글 조회
GET http://localhost:8080/comments/1
Authorization: {{USER1_TOKEN}}

### 댓글 수정
PUT http://localhost:8080/comments/1
Content-Type: application/json
Authorization: {{USER1_TOKEN}}

{
  "content": "This is an updated comment2."
}

### 댓글 삭제
DELETE http://localhost:8080/comments/4
Authorization: {{USER1_TOKEN}}
